version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: myapp/backend
    networks:
      - frontend_net
      - backend_net
    ports:
      - "${BACKEND_PORT}:3001"
    depends_on:
      - database
    env_file:
      - ./.env
  frontend:
    build:
      context: ./frontend
    image: myapp/frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - frontend_net
    depends_on:
      - database
    env_file:
      - ./.env
  database:
    build:
      context: ./database
    image: myapp/database
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"


networks:
  backend_net:
  frontend_net:

volumes:
  db_data:
